/**
 * goalPresets.js — Canonical financial goal preset templates.
 * 
 * Provides sensible starting targets, recommended contribution levels,
 * icons, and priorities for common financial milestones.
 */

export const GOAL_PRESETS = [
  {
    id: 'emergency_fund',
    icon: '🛡️',
    title: 'Emergency Fund (6 Months)',
    description: 'Safety cushion covering 6 months of essential living expenses.',
    targetAmount: '300000',
    monthlyContribution: '15000',
    priority: 'high',
    targetMonthsAhead: 20,
  },
  {
    id: 'vacation',
    icon: '🏖️',
    title: 'Dream Vacation & Travel',
    description: 'Flights, stay, and spending money for an international or getaway trip.',
    targetAmount: '120000',
    monthlyContribution: '10000',
    priority: 'medium',
    targetMonthsAhead: 12,
  },
  {
    id: 'vehicle',
    icon: '🚗',
    title: 'Car / Vehicle Down Payment',
    description: 'Down payment for a new vehicle purchase.',
    targetAmount: '250000',
    monthlyContribution: '12500',
    priority: 'medium',
    targetMonthsAhead: 20,
  },
  {
    id: 'home_downpayment',
    icon: '🏡',
    title: 'House / Apartment Down Payment',
    description: 'Long-term savings fund for down payment and home registration costs.',
    targetAmount: '1000000',
    monthlyContribution: '25000',
    priority: 'high',
    targetMonthsAhead: 40,
  },
  {
    id: 'tech_upgrade',
    icon: '💻',
    title: 'Tech & Workstation Upgrade',
    description: 'Upgrading laptop, monitor, and productive home office equipment.',
    targetAmount: '150000',
    monthlyContribution: '12500',
    priority: 'low',
    targetMonthsAhead: 12,
  },
  {
    id: 'education',
    icon: '🎓',
    title: 'Education & Professional Certifications',
    description: 'Course fees, degree programs, or executive tech certificates.',
    targetAmount: '80000',
    monthlyContribution: '8000',
    priority: 'high',
    targetMonthsAhead: 10,
  },
  {
    id: 'wedding',
    icon: '💍',
    title: 'Wedding & Family Celebration',
    description: 'Savings dedicated for venue, celebrations, and festive ceremonies.',
    targetAmount: '500000',
    monthlyContribution: '20000',
    priority: 'medium',
    targetMonthsAhead: 25,
  },
  {
    id: 'debt_payoff',
    icon: '💳',
    title: 'Accelerated Debt / Loan Payoff',
    description: 'Clearing credit card balance or personal loan ahead of schedule.',
    targetAmount: '200000',
    monthlyContribution: '15000',
    priority: 'high',
    targetMonthsAhead: 14,
  },
];
