"""Add OAuthCode model

Revision ID: 51f5773d7ecd
Revises: e12a_perf_indexes
Create Date: 2026-08-19 04:54:47.138964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51f5773d7ecd'
down_revision: Union[str, None] = 'e12a_perf_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_codes',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_codes_code_hash'), 'oauth_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_oauth_codes_created_at'), 'oauth_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_oauth_codes_id'), 'oauth_codes', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_budgets_created_at'), 'budgets', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_goal_contributions_created_at'), 'goal_contributions', ['created_at'], unique=False)
    op.create_index(op.f('ix_goals_created_at'), 'goals', ['created_at'], unique=False)
    op.create_index(op.f('ix_incomes_created_at'), 'incomes', ['created_at'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'SYSTEM'::character varying"))
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_type_created', 'notifications', ['user_id', 'type', 'created_at'], unique=False)
    op.alter_column('recurring_transactions', 'type',
               existing_type=postgresql.ENUM('INCOME', 'EXPENSE', name='transactiontype'),
               type_=sa.Enum('INCOME', 'EXPENSE', name='transactiontype', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('recurring_transactions', 'frequency',
               existing_type=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurringfrequency'),
               type_=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='recurringfrequency', native_enum=False, length=50),
               existing_nullable=False)
    op.alter_column('recurring_transactions', 'start_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('recurring_transactions', 'is_never_ending',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('recurring_transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('recurring_transactions', 'auto_process',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_recurring_transactions_created_at'), 'recurring_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_status'), 'recurring_transactions', ['status'], unique=False)
    op.create_index('ix_recurring_user_status_next', 'recurring_transactions', ['user_id', 'status', 'next_date'], unique=False)
    op.create_index('ix_recurring_user_type', 'recurring_transactions', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_reminder_histories_created_at'), 'reminder_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_reminder_histories_id'), 'reminder_histories', ['id'], unique=False)
    op.create_index('ix_reminder_histories_user_date', 'reminder_histories', ['user_id', 'action_date'], unique=False)
    op.create_index(op.f('ix_reminders_category_id'), 'reminders', ['category_id'], unique=False)
    op.create_index(op.f('ix_reminders_created_at'), 'reminders', ['created_at'], unique=False)
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_type'), 'reminders', ['type'], unique=False)
    op.create_index('ix_reminders_user_status_due', 'reminders', ['user_id', 'status', 'due_date'], unique=False)
    op.create_index('ix_reminders_user_type', 'reminders', ['user_id', 'type'], unique=False)
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), server_default='email', nullable=False))
    op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'auth_provider')
    op.drop_index('ix_reminders_user_type', table_name='reminders')
    op.drop_index('ix_reminders_user_status_due', table_name='reminders')
    op.drop_index(op.f('ix_reminders_type'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_created_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_category_id'), table_name='reminders')
    op.drop_index('ix_reminder_histories_user_date', table_name='reminder_histories')
    op.drop_index(op.f('ix_reminder_histories_id'), table_name='reminder_histories')
    op.drop_index(op.f('ix_reminder_histories_created_at'), table_name='reminder_histories')
    op.drop_index('ix_recurring_user_type', table_name='recurring_transactions')
    op.drop_index('ix_recurring_user_status_next', table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_status'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_created_at'), table_name='recurring_transactions')
    op.alter_column('recurring_transactions', 'auto_process',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('recurring_transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('recurring_transactions', 'is_never_ending',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('recurring_transactions', 'start_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('recurring_transactions', 'frequency',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='recurringfrequency', native_enum=False, length=50),
               type_=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurringfrequency'),
               existing_nullable=False)
    op.alter_column('recurring_transactions', 'type',
               existing_type=sa.Enum('INCOME', 'EXPENSE', name='transactiontype', native_enum=False, length=50),
               type_=postgresql.ENUM('INCOME', 'EXPENSE', name='transactiontype'),
               existing_nullable=False)
    op.drop_index('ix_notifications_user_type_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.alter_column('notifications', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'SYSTEM'::character varying"))
    op.drop_index(op.f('ix_incomes_created_at'), table_name='incomes')
    op.drop_index(op.f('ix_goals_created_at'), table_name='goals')
    op.drop_index(op.f('ix_goal_contributions_created_at'), table_name='goal_contributions')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_index(op.f('ix_budgets_created_at'), table_name='budgets')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_oauth_codes_id'), table_name='oauth_codes')
    op.drop_index(op.f('ix_oauth_codes_created_at'), table_name='oauth_codes')
    op.drop_index(op.f('ix_oauth_codes_code_hash'), table_name='oauth_codes')
    op.drop_table('oauth_codes')
    # ### end Alembic commands ###
