"""fix_expense_category_schema

Revision ID: 8a5ef6cb224c
Revises: 0001
Create Date: 2026-07-27 13:03:36.015372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5ef6cb224c'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('expenses', sa.Column('merchant', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.add_column('expenses', sa.Column('receipt_url', sa.String(length=1024), nullable=True))
    op.alter_column('expenses', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('incomes', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'description')
    op.alter_column('expenses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('expenses', 'receipt_url')
    op.drop_column('expenses', 'payment_method')
    op.drop_column('expenses', 'merchant')
    op.alter_column('categories', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
