"""add_description_and_priority_to_goals

Revision ID: cdd8e42dcf55
Revises: 8a5ef6cb224c
Create Date: 2026-07-27 14:42:47.001951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd8e42dcf55'
down_revision: Union[str, None] = '8a5ef6cb224c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('goals', sa.Column('priority', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'priority')
    op.drop_column('goals', 'description')
    # ### end Alembic commands ###
